import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
        flex:1,
      backgroundColor:'white'
    },
    headconatiner:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    head:{
       width:'90%',
      paddingVertical:27,
      
    },
    headtxt:{
        color:'black',
        fontWeight:'600',
        fontSize:15
    },
    logocontainer:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center',
        paddingVertical:10
    },
    loginformcontainer:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center',
        marginVertical:10
    },
    loginform:{
      width:'90%',
      alignItems:'center',
      justifyContent:'center'
    },
    input:{
        width:'100%',
        borderWidth:1,
        borderColor:'#F49627',
        marginVertical:10,
        borderRadius:35,
        padding:8,
        paddingHorizontal:16
    },
    placeholderstyle:{
        color:'black',

    },
    paswordcontainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    fpcontainer:{
        flexDirection:'row',
        width:'90%',
        padding:5,
        alignItems:'flex-end',
        justifyContent:'flex-end'
    },
    fptxt:{
        fontSize:12,
        color:'black',
     
    },
    btncontainer:{
        width:'100%',
        backgroundColor:'#F49627',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        padding:20,
        paddingHorizontal:16,
        borderRadius:35,
        marginVertical:10
    },
    btntxt:{
        color:'white',
        fontWeight:'700',
        fontSize:15,
        fontFamily:'Inter-Regular'
    },
    signuptxtcontainer:{
        width:'90%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    signuptxt:{
        color:'black',

    },
    signtxt:{
        color:'#F49627'
    },
    signupor:{
        marginVertical:10,
        color:'black'
    },
    otherlogcontainer:{
      width:'100%',
      alignItems:'center',
      justifyContent:'center',
      marginTop:40
    },
    optbox:{
        width:'90%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    logo:{
        width:30,
        height:30
    },
    logobtn:{
        marginHorizontal:10
    }
})
export default styles