import {StyleSheet} from 'react-native'

const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'white',
        
    },
    logocontainer:{
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        marginVertical:50
    },
    headcontainer:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center',
        
    },
    headtxt:{
        color:'black',
        fontSize:18,
        fontWeight:'bold'
    },
    inputcontainer:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    inputbox:{
        width:'90%',
        borderWidth:1,
        borderColor:'#F49627',
        marginVertical:50,
        borderRadius:35,
        padding:10,
        paddingHorizontal:16
    },
    btncontainer:{
        width:'90%',
        backgroundColor:'#F49627',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        padding:17,
        paddingHorizontal:16,
        borderRadius:35,
      
    },
    btntxt:{
        color:'white',
        fontWeight:'500',
        fontSize:18
    },
    otpcontainer:{
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    otpbox:{
        width:'90%',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center'
    },
    infotxt:{
        color:'black'
    },
    otpinput:{
        width:'90%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    otpinp:{
        width:50,
        flexDirection:'row',
        alignItems:'center',
        borderRadius:10,
        justifyContent:'center',
        borderWidth:1,
        borderColor:'#F49627',
        textAlign:'center',
        marginHorizontal:6
    },
    confirmcontainer:{
        width:'100%',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        marginVertical:35
    },
    timercontainer:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    timertxt:{
        color:'black'
    },
    resetpasscontainer:{
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        marginVertical:18
    },
    resetpasswordbox:{
        width:'90%',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center'
    },
    resinp:{
        width:'95%',
        borderWidth:1,
        borderColor:'#F49627',
        borderRadius:35,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        padding:10,
        paddingHorizontal:20,
        marginVertical:10
    },
    resbtncontainer:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center',
        marginVertical:15
    }
})
export default styles